version: '3' 
services:
  mysql:
    image: mysql
    container_name: mercadolivre-bd
    environment:      
      - MYSQL_ROOT_PASSWORD=root      
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - mysql-network

  java:
    build:
      dockerfile: ./docker/mercadolivre.dockerfile
      context: .
    image: gustavo/mercadolivre
    container_name: mercadolivre-api    
    environment: 
      SPRING_DATASOURCE_URL: jdbc:mysql://mercadolivre-bd:3306/mercado_livre?createDatabaseIfNotExist=true    
    ports: 
      - "8080:8080"  
    depends_on:
      - "mysql"
    networks:
      - mysql-network

networks:
    mysql-network:
      driver: bridge